# Travis CI configuration file for a WordPoints extension.

language: php

env:
    - TRAVISCI_RUN=codesniff

dist: trusty

sudo: false

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

matrix:
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    # Use Ubuntu Precise because Trusty doesn't support PHP 5.2 or 5.3.
    - php: 5.3
      dist: precise
      env: TRAVISCI_RUN=codesniff DO_PHPCS=0
    - php: 5.2
      dist: precise
      env: TRAVISCI_RUN=codesniff DO_PHPCS=0
    # Run against nightly.
    - php: nightly
  allow_failures:
    - php: nightly
    - php: 7.2
  fast_finish: true

before_script:
    - export WORDPOINTS_PROJECT_TYPE=extension
    - export DEV_LIB_PATH=dev-lib
    - if [ -e .wordpoints-dev-lib-config.sh ]; then source .wordpoints-dev-lib-config.sh; fi
    - source $DEV_LIB_PATH/travis/before_script.sh

script:
    - codesniff-php-syntax
    - codesniff-phpcs
    - codesniff-strings
    - codesniff-dittography
    - codesniff-l10n
    - codesniff-xmllint
    - codesniff-bash
    - codesniff-symlinks

after_script:
    - source $DEV_LIB_PATH/travis/after_script.sh
